#!/bin/sh 
modulo=4
#count page numbers
p=$(pdfinfo $1 | grep Pages | sed 's/[^0-9]*//') 
# prepare for removal of backcover
endpage=$(($p - 4))  #remove ad
effectivepages=$(($p - 4)) 
blankpagenumber=$(($p - 3))  
# compute how many blank pages to add
n=$(($modulo -  $effectivepages % modulo))  
if [ $n -eq 4 ]; then 
  n=0;
fi
echo $n
# start with no blank pages
b=''
#accumulate Bs until we reach a multiple
while [ $n -ne 0 ]; do
  b=$b\ $blankpagenumber
  n=$(($n - 1))
  done 
# strip front and back cover and add blank pages to meet multiple of modulo
pdftk $1 cat $blankpagenumber 2-$endpage $b output $2

